-- Create the database 'gad'
CREATE DATABASE IF NOT EXISTS gad;

-- Switch to the 'gad' database
USE gad;

CREATE TABLE IF NOT EXISTS `ra7877` (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    totalScore INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `ra9262` (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    totalScore INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `ra9710` (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    totalScore INT NOT NULL
);

CREATE TABLE IF NOT EXISTS `ra11313` (
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(255) NOT NULL,
    totalScore INT NOT NULL
);
